PEMS08:
  num_nodes: 170
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.01
  epsilon: 0.001
  weight_decay: 0.01
  milestones: [ 35, 55, 75]
  lr_decay_ratio: 0.1
  batch_size: 32
  epochs: 100
  early_stop: 30
  use_cl: False
  cl_step_size: 2500
  lamb1: 0.1
  lamb2: 0.1
  max_grad_norm: 5.0
  seed: 80


  model_args:
    num_nodes: 170
    input_dim: 1
    output_dim: 1
    horizon: 12
    rnn_units: 64
    num_layers: 1
    cheb_k: 3
    ycov_dim: 2
    mem_num: 100
    mem_dim: 64
    cl_decay_steps: 2000
    use_curriculum_learning: True
    
PEMS04:
  num_nodes: 307
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.01
  epsilon: 0.001
  weight_decay: 0.01
  milestones: [ 35, 55, 75]
  lr_decay_ratio: 0.1
  batch_size: 32
  epochs: 100
  early_stop: 30
  use_cl: False
  cl_step_size: 2500
  lamb1: 0.1
  lamb2: 0.1
  max_grad_norm: 5.0
  seed: 42


  model_args:
    num_nodes: 307
    input_dim: 1
    output_dim: 1
    horizon: 12
    rnn_units: 64
    num_layers: 1
    cheb_k: 3
    ycov_dim: 2
    mem_num: 100
    mem_dim: 64
    cl_decay_steps: 2000
    use_curriculum_learning: True

PEMS03:
  num_nodes: 358
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.01
  epsilon: 0.001
  weight_decay: 0.01
  milestones: [ 35, 55, 75]
  lr_decay_ratio: 0.1
  batch_size: 32
  epochs: 100
  early_stop: 30
  use_cl: False
  cl_step_size: 2500
  lamb1: 0.1
  lamb2: 0.1
  max_grad_norm: 5.0
  seed: 30


  model_args:
    num_nodes: 358
    input_dim: 1
    output_dim: 1
    horizon: 12
    rnn_units: 64
    num_layers: 1
    cheb_k: 3
    ycov_dim: 2
    mem_num: 100
    mem_dim: 64
    cl_decay_steps: 2000
    use_curriculum_learning: True
    
MERT-LA:
  num_nodes: 307
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True

  lr: 0.01
  epsilon: 0.001
  weight_decay: 0.01
  milestones: [ 35, 55, 75]
  lr_decay_ratio: 0.1
  batch_size: 32
  epochs: 100
  early_stop: 30
  use_cl: False
  cl_step_size: 2500
  lamb1: 0.1
  lamb2: 0.1
  max_grad_norm: 5.0
  seed: 50


  model_args:
    num_nodes: 307
    input_dim: 1
    output_dim: 1
    horizon: 12
    rnn_units: 64
    num_layers: 1
    cheb_k: 3
    ycov_dim: 2
    mem_num: 100
    mem_dim: 64
    cl_decay_steps: 2000
    use_curriculum_learning: True

PEMS-BAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True

  lr: 0.01
  epsilon: 0.001
  weight_decay: 0.01
  milestones: [ 35, 55, 75]
  lr_decay_ratio: 0.1
  batch_size: 32
  epochs: 100
  early_stop: 30
  use_cl: False
  cl_step_size: 2500
  lamb1: 0.1
  lamb2: 0.1
  max_grad_norm: 5.0
  seed: 90


  model_args:
    num_nodes: 325
    input_dim: 1
    output_dim: 1
    horizon: 12
    rnn_units: 64
    num_layers: 1
    cheb_k: 3
    ycov_dim: 2
    mem_num: 100
    mem_dim: 64
    cl_decay_steps: 2000
    use_curriculum_learning: True
    


